"""Generate procedural game files: sample specs, keep only the ones where
every level is solvable (`procedural/solver.py`), write each as a `.py`
game file `arc_agi`'s local loader can run exactly like a public game, and
report measurable diversity over the accepted set — the Fase 1 deliverable
(`docs/design.md` §7: "N juegos sintéticos con diversidad medible de
mecánicas").

Usage:
    .venv/bin/python -m procedural.generate --count 100
    .venv/bin/python -m procedural.generate --count 20 --play-check 5
"""
from __future__ import annotations

import argparse
import json
import random
from collections import Counter
from dataclasses import asdict
from pathlib import Path

from .mechanics import PRIMARY_MECHANICS
from .solver import solve_all_levels
from .spec import GameSpec, sample_spec

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT_DIR = ROOT / "procedural_games"

GAME_FILE_TEMPLATE = '''\
"""Generated by procedural/generate.py — do not edit by hand."""
import sys
sys.path.insert(0, {root!r})

from procedural.engine import ProceduralGame
from procedural.spec import GameSpec

SPEC = GameSpec(
    seed={seed!r},
    width={width!r},
    height={height!r},
    primary_key={primary_key!r},
    primary_params={primary_params!r},
    hazard_key={hazard_key!r},
    hazard_params={hazard_params!r},
    num_levels={num_levels!r},
    role_colors={role_colors!r},
)


class {class_name}(ProceduralGame):
    SPEC = SPEC
'''


def write_game_file(spec: GameSpec, game_id: str, class_name: str, output_dir: Path) -> Path:
    game_dir = output_dir / game_id
    game_dir.mkdir(parents=True, exist_ok=True)
    path = game_dir / f"{class_name.lower()}.py"
    path.write_text(
        GAME_FILE_TEMPLATE.format(root=str(ROOT), class_name=class_name, **asdict(spec)),
        encoding="utf-8",
    )
    return path


def generate(count: int, seed: int, output_dir: Path, max_attempts_per_game: int = 20) -> list[dict]:
    """Samples `count` distinct, fully-solvable specs (resampling on
    rejection, up to `max_attempts_per_game` tries each) and writes them
    out. Returns the manifest entries (also written to
    `<output_dir>/manifest.json`).
    """
    rng = random.Random(seed)
    manifest: list[dict] = []
    seen_specs: set[tuple] = set()
    attempts = 0
    rejected = 0

    while len(manifest) < count:
        attempts += 1
        spec_seed = rng.randrange(2**31)
        spec = sample_spec(rng, seed=spec_seed)
        dedup_key = (
            spec.primary_key, spec.width, spec.height, spec.hazard_key,
            tuple(sorted(spec.primary_params.items())), spec.num_levels,
        )
        if dedup_key in seen_specs:
            continue
        solutions = solve_all_levels(spec)
        if solutions is None:
            rejected += 1
            if attempts > count * max_attempts_per_game:
                break
            continue
        seen_specs.add(dedup_key)

        index = len(manifest)
        game_id = f"proc{index:05d}"
        class_name = f"Proc{index:05d}"
        path = write_game_file(spec, game_id, class_name, output_dir)
        manifest.append(
            {
                "game_id": game_id,
                "class_name": class_name,
                "local_dir": str(path.parent),
                "solution_lengths": [len(s) for s in solutions],
                **asdict(spec),
            }
        )

    output_dir.mkdir(parents=True, exist_ok=True)
    (output_dir / "manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    print(f"Generated {len(manifest)}/{count} requested games "
          f"({attempts} spec attempts, {rejected} rejected as unsolvable).")
    return manifest


def diversity_report(manifest: list[dict]) -> None:
    print("\n========= DIVERSITY REPORT =========")
    print(f"total games: {len(manifest)}")

    by_primary = Counter(m["primary_key"] for m in manifest)
    print(f"\nprimary mechanic coverage ({len(by_primary)}/{len(PRIMARY_MECHANICS)} available used):")
    for key in sorted(PRIMARY_MECHANICS):
        print(f"  {key:22} {by_primary.get(key, 0)}")

    by_hazard = Counter(m["hazard_key"] or "(none)" for m in manifest)
    print(f"\nhazard modifier coverage:")
    for key, n in sorted(by_hazard.items()):
        print(f"  {key:22} {n}")

    directional = sum(1 for m in manifest if PRIMARY_MECHANICS[m["primary_key"]].directional)
    print(f"\nmodality: {directional} directional, {len(manifest) - directional} click-based")

    combos = {(m["primary_key"], m["hazard_key"]) for m in manifest}
    print(f"\ndistinct (mechanic, hazard) combinations: {len(combos)}")

    sizes = [(m["width"], m["height"]) for m in manifest]
    print(f"grid size range: {min(sizes)} .. {max(sizes)}")

    levels = [m["num_levels"] for m in manifest]
    print(f"levels per game: min={min(levels)} max={max(levels)} mean={sum(levels)/len(levels):.1f}")

    sol_lens = [n for m in manifest for n in m["solution_lengths"]]
    print(f"solution length per level: min={min(sol_lens)} max={max(sol_lens)} mean={sum(sol_lens)/len(sol_lens):.1f}")


def play_check(manifest: list[dict], n: int) -> None:
    """Loads `n` generated games through `arc_agi`'s real local loader (not
    our own test harness) and plays a few random legal actions through
    each, to confirm the generated files are actually consumable by the
    same pipeline `scripts/play_local.py`/`scripts/evaluate.py` use.
    """
    import sys

    sys.path.insert(0, str(ROOT))
    vendor = ROOT / "vendor" / "ARC-AGI-3-Agents"
    if vendor.exists():
        sys.path.insert(0, str(vendor))

    from arc_agi.local_wrapper import LocalEnvironmentWrapper
    from arc_agi.models import EnvironmentInfo
    from arcengine import GameAction

    print(f"\n========= PLAY CHECK ({min(n, len(manifest))} games) =========")
    sample = random.Random(0).sample(manifest, min(n, len(manifest)))
    for entry in sample:
        info = EnvironmentInfo(
            game_id=entry["game_id"], class_name=entry["class_name"], local_dir=entry["local_dir"]
        )
        wrapper = LocalEnvironmentWrapper(
            environment_info=info, logger=__import__("logging").getLogger("play_check"), scorecard_id="check"
        )
        rng = random.Random(1)
        actions = [a for a in GameAction if a is not GameAction.RESET]
        ok = wrapper.reset() is not None
        for _ in range(10):
            action = rng.choice(actions)
            data = {"x": rng.randrange(64), "y": rng.randrange(64)} if action.is_complex() else {}
            frame = wrapper.step(action, data=data)
            ok = ok and frame is not None
        print(f"  {entry['game_id']} ({entry['primary_key']}, hazard={entry['hazard_key']}): "
              f"{'OK' if ok else 'FAILED'}")


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--count", type=int, default=100)
    p.add_argument("--seed", type=int, default=0)
    p.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    p.add_argument("--play-check", type=int, default=0,
                   help="Load this many generated games through arc_agi's real loader "
                        "and play a few random actions through each, as a sanity check.")
    args = p.parse_args()

    manifest = generate(args.count, args.seed, args.output_dir)
    diversity_report(manifest)
    if args.play_check:
        play_check(manifest, args.play_check)


if __name__ == "__main__":
    main()
